FS_SUB_DOMAIN_EMPHASIS = {
    "banking_capital": "capital adequacy, Basel III/IV requirements, RWA calculations, stress testing, and ICAAP",
    "payments_settlement": "payment system resilience, settlement finality, intraday liquidity, and operational continuity",
    "consumer_protection": "fair lending, UDAAP compliance, disclosure requirements, and dispute resolution",
    "aml_kyc": "customer due diligence, beneficial ownership, transaction monitoring, and SAR filing",
    "data_privacy_fintech": "data governance, open banking, third-party risk, and consumer consent frameworks",
    "general": "broad regulatory compliance across risk management, governance, and disclosure obligations",
}


def get_fs_action_plan_template(
    regulation_name: str,
    issuing_body: str,
    effective_date: str,
    sub_domain: str,
    jurisdiction: str,
    clauses_summary: str,
    impact_summary: str,
    critical_count: int,
    high_count: int,
    medium_count: int,
    low_count: int,
) -> str:
    emphasis = FS_SUB_DOMAIN_EMPHASIS.get(sub_domain, FS_SUB_DOMAIN_EMPHASIS["general"])
    return f"""You are a senior regulatory compliance consultant specializing in financial services.
Generate a detailed, professional compliance action plan in structured Markdown.

REGULATION: {regulation_name or "Unknown Regulation"}
ISSUING BODY: {issuing_body or "Unknown"}
EFFECTIVE DATE: {effective_date or "TBD"}
JURISDICTION: {jurisdiction or "Unknown"}
SUB-DOMAIN FOCUS: {emphasis}

EXTRACTED CLAUSES AND IMPACT SUMMARY:
{clauses_summary}

SEVERITY BREAKDOWN:
- Critical: {critical_count} clauses
- High: {high_count} clauses
- Medium: {medium_count} clauses
- Low: {low_count} clauses

IMPACT DETAILS:
{impact_summary}

Generate a comprehensive compliance action plan with EXACTLY these sections:

# Compliance Action Plan: {regulation_name or "Regulatory Analysis"}

## Executive Summary
[3-4 sentences: regulation scope, key compliance obligations, urgency level based on severity counts]

## Regulatory Scope
[Jurisdiction, effective date, covered entities, exemptions if any]

## Key Requirements by Function

### Risk Management
[Requirements affecting Risk Management function]

### Compliance & Legal
[Requirements affecting Compliance & Legal function]

### IT & Cybersecurity
[Requirements affecting IT & Cybersecurity function]

### Operations & Reporting
[Requirements affecting Operations and Reporting & Disclosure functions]

### Capital Planning & Treasury
[Requirements affecting Capital Planning and Treasury functions]

### Customer Onboarding & Audit
[Requirements affecting Customer Onboarding and Internal Audit functions]

## Prioritized Action Items

| Priority | Action | Responsible Function | Estimated Effort | Dependencies |
|----------|--------|----------------------|------------------|--------------|
[Generate 8-12 rows from the extracted action items, sorted by priority then severity]

## Compliance Timeline

| Phase | Timeline | Key Milestones |
|-------|----------|----------------|
| Immediate (0-30 days) | [date range] | [actions] |
| Short-term (1-3 months) | [date range] | [actions] |
| Long-term (3-12 months) | [date range] | [actions] |

## Regulatory Interaction Risk
[Financial-services-specific section: identify clauses that interact with existing regulations (Basel III, DORA, MiFID II, AML Directive, etc.), potential conflicts, and regulatory overlap considerations]

## Resources & References
- [Regulation full text or issuing body URL]
- Relevant industry guidance (BIS, FSB, FATF as applicable)
- Internal policy frameworks that require updating

---
*Generated by Regulatory Impact Analysis Agent | {regulation_name or "Analysis"} | Financial Services*
"""
