HC_SUB_DOMAIN_EMPHASIS = {
    "pharma_clinical_trials": "IND/NDA submissions, clinical trial protocols, GCP compliance, and trial monitoring",
    "medical_devices": "510(k)/PMA submissions, design controls, post-market surveillance, and UDI requirements",
    "data_privacy_hipaa": "PHI safeguards, Business Associate Agreements, breach notification, and minimum necessary standards",
    "pharmacovigilance": "adverse event reporting, REMS requirements, signal detection, and safety database management",
    "billing_coding": "ICD/CPT coding accuracy, claims submission, audit controls, and revenue cycle compliance",
    "general": "broad healthcare regulatory compliance across quality, safety, and data governance obligations",
}


def get_hc_action_plan_template(
    regulation_name: str,
    issuing_body: str,
    effective_date: str,
    sub_domain: str,
    jurisdiction: str,
    clauses_summary: str,
    impact_summary: str,
    critical_count: int,
    high_count: int,
    medium_count: int,
    low_count: int,
) -> str:
    emphasis = HC_SUB_DOMAIN_EMPHASIS.get(sub_domain, HC_SUB_DOMAIN_EMPHASIS["general"])
    return f"""You are a senior healthcare regulatory compliance consultant with expertise in FDA, CMS, and EMA regulations.
Generate a detailed, professional compliance action plan in structured Markdown.

REGULATION: {regulation_name or "Unknown Regulation"}
ISSUING BODY: {issuing_body or "Unknown"}
EFFECTIVE DATE: {effective_date or "TBD"}
JURISDICTION: {jurisdiction or "Unknown"}
SUB-DOMAIN FOCUS: {emphasis}

EXTRACTED CLAUSES AND IMPACT SUMMARY:
{clauses_summary}

SEVERITY BREAKDOWN:
- Critical: {critical_count} clauses
- High: {high_count} clauses
- Medium: {medium_count} clauses
- Low: {low_count} clauses

IMPACT DETAILS:
{impact_summary}

Generate a comprehensive compliance action plan with EXACTLY these sections:

# Compliance Action Plan: {regulation_name or "Regulatory Analysis"}

## Executive Summary
[3-4 sentences: regulation scope, key compliance obligations, patient safety implications, and urgency level based on severity counts]

## Regulatory Scope
[Jurisdiction, effective date, covered entities (manufacturers, providers, payers, etc.), exemptions if any]

## Key Requirements by Function

### Clinical Operations
[Requirements affecting Clinical Operations function]

### Quality Assurance
[Requirements affecting Quality Assurance function]

### Regulatory Affairs
[Requirements affecting Regulatory Affairs function]

### IT & Data Systems
[Requirements affecting IT & Data Systems, especially PHI handling]

### Pharmacovigilance & Medical Affairs
[Requirements affecting Pharmacovigilance and Medical Affairs functions]

### Finance & Billing
[Requirements affecting Finance & Billing function]

## Prioritized Action Items

| Priority | Action | Responsible Function | Estimated Effort | Dependencies |
|----------|--------|----------------------|------------------|--------------|
[Generate 8-12 rows from the extracted action items, sorted by priority then severity]

## Compliance Timeline

| Phase | Timeline | Key Milestones |
|-------|----------|----------------|
| Immediate (0-30 days) | [date range] | [actions] |
| Short-term (1-3 months) | [date range] | [actions] |
| Long-term (3-12 months) | [date range] | [actions] |

## Patient Safety Prioritization
[Healthcare-specific section: identify clauses with direct patient safety implications, required escalation protocols, safety reporting obligations, and CAPA (Corrective and Preventive Action) requirements]

## Resources & References
- [Regulation full text or issuing body URL (FDA.gov, CMS.gov, EMA.europa.eu)]
- ICH guidelines as applicable (ICH E6, ICH Q10, etc.)
- Internal SOPs and quality management documents requiring updates

---
*Generated by Regulatory Impact Analysis Agent | {regulation_name or "Analysis"} | Healthcare*
"""
