import logging

from langchain_ollama import ChatOllama
from langchain_core.messages import HumanMessage

from config import OLLAMA_BASE_URL, OLLAMA_MODEL, LLM_TEMPERATURE
from agents.state import ResearchState, CitationResult

logger = logging.getLogger(__name__)


def _build_citation_context(citations: list[CitationResult]) -> str:
    """Build a numbered citation block for the LLM prompt."""
    usable = [c for c in citations if c["is_usable"]]
    unusable = [c for c in citations if not c["is_usable"]]

    lines = []
    idx = 1
    for c in usable:
        claims_text = "; ".join(c["key_claims"][:5]) or "No claims extracted"
        lines.append(
            f"[{idx}] {c['domain']} (confidence={c['confidence_score']:.2f}, USABLE)\n"
            f"    Claims: {claims_text}"
        )
        idx += 1
    for c in unusable:
        claims_text = "; ".join(c["key_claims"][:3]) or "No claims extracted"
        lines.append(
            f"[{idx}] {c['domain']} (confidence={c['confidence_score']:.2f}, LOW-CONFIDENCE)\n"
            f"    Claims: {claims_text}"
        )
        idx += 1

    return "\n".join(lines)


def _compute_overall_confidence(citations: list[CitationResult]) -> float:
    usable = [c for c in citations if c["is_usable"]]
    if not usable:
        return 0.0
    return round(sum(c["confidence_score"] for c in usable) / len(usable), 4)


def write_report(state: ResearchState) -> ResearchState:
    """Agent 3: Write a structured Markdown research report via LLM."""
    topic = state["topic"]
    citations = state["citations"]
    progress: list[str] = list(state.get("progress_messages", []))

    progress.append("[report_writer] Starting — compiling report...")

    overall_confidence = _compute_overall_confidence(citations)
    citation_context = _build_citation_context(citations)

    usable_count = sum(1 for c in citations if c["is_usable"])
    total_count = len(citations)

    # Build source assessment table rows
    table_rows = []
    for i, c in enumerate(citations, 1):
        status = "✓ Usable" if c["is_usable"] else "✗ Low-confidence"
        table_rows.append(
            f"| {i} | {c['domain']} | {c['confidence_score']:.2f} | {status} |"
        )
    table_str = "\n".join(table_rows)

    prompt = (
        f"You are writing a professional research report.\n\n"
        f"Research topic: {topic}\n"
        f"Overall confidence score: {overall_confidence:.2f}/1.0\n"
        f"Sources analyzed: {total_count} total, {usable_count} usable\n\n"
        f"Sources and claims:\n{citation_context}\n\n"
        f"Write a structured Markdown research report with exactly these sections:\n\n"
        f"# Research Report: {topic}\n\n"
        f"**Overall Confidence: {overall_confidence:.1f}/1.0** | "
        f"**Sources: {usable_count}/{total_count} usable**\n\n"
        f"## Executive Summary\n"
        f"(2-3 paragraph summary of the research findings)\n\n"
        f"## Key Findings\n"
        f"(Bullet list of the most important findings, use inline [N] citations)\n\n"
        f"## Detailed Analysis\n"
        f"(Deeper analysis of findings with inline [N] citations referencing the sources)\n\n"
        f"## Source Assessment\n"
        f"| # | Domain | Confidence | Status |\n"
        f"|---|--------|------------|--------|\n"
        f"{table_str}\n\n"
        f"## References\n"
        f"(Numbered list matching the citation numbers used above)\n\n"
        f"Use ONLY information from the provided sources. "
        f"Be factual, cite sources inline with [N] notation. "
        f"Do not add any preamble or postamble outside the report structure."
    )

    logger.info("Invoking LLM for report generation...")

    llm = ChatOllama(
        base_url=OLLAMA_BASE_URL,
        model=OLLAMA_MODEL,
        temperature=LLM_TEMPERATURE,
    )

    try:
        response = llm.invoke([HumanMessage(content=prompt)])
        report = response.content.strip()
    except Exception as e:
        logger.error(f"Report generation failed: {e}")
        report = (
            f"# Research Report: {topic}\n\n"
            f"**Error**: Report generation failed — {e}\n\n"
            f"## Sources Analyzed\n{citation_context}"
        )

    report += "\n\n---\n*Generated by Multi-Agent Research System*"

    progress.append("[report_writer] Report complete.")

    return {
        **state,
        "report_markdown": report,
        "overall_confidence": overall_confidence,
        "progress_messages": progress,
        "current_agent": "done",
    }
